version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  gateway_service:
#    image: puzanovim/gateway_service:v1
    build: gateway_service
    container_name: gateway_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - notes_service
      - category_service
      - namespace_service
      - statistic_service
      - identity_provider

  notes_service:
#    image: puzanovim/notes_service:v1
    build: notes_service
    container_name: notes_service
    restart: always
    ports:
      - "8070:8070"
    depends_on:
      - postgres

  category_service:
#    image: puzanovim/category_service:v1
    build: category_service
    container_name: category_service
    restart: always
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  namespace_service:
#    image: puzanovim/namespace_service:v1
    build: namespace_service
    container_name: namespace_service
    restart: always
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  statistic_service:
#    image: puzanovim/statistic_service:v1
    build: statistic_service
    container_name: statistic_service
    restart: always
    ports:
      - "8040:8040"
    depends_on:
      - postgres

  identity_provider:
#    image: puzanovim/identity_provider:v1
    build: identity_provider
    container_name: identity_provider
    restart: always
    ports:
      - "8030:8030"
    depends_on:
      - postgres

  frontend:
#    image: puzanovim/frontend:v1
    build: frontend
    container_name: frontend
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - gateway_service

volumes:
  db-data: