CREATE DATABASE categories;
GRANT ALL PRIVILEGES ON DATABASE categories TO program;

CREATE DATABASE notes;
GRANT ALL PRIVILEGES ON DATABASE notes TO program;

CREATE DATABASE namespaces;
GRANT ALL PRIVILEGES ON DATABASE namespaces TO program;

CREATE DATABASE statistics;
GRANT ALL PRIVILEGES ON DATABASE statistics TO program;

CREATE DATABASE users;
GRANT ALL PRIVILEGES ON DATABASE users TO program;