"""init

Revision ID: eb622ee85325
Revises: 
Create Date: 2023-05-31 18:50:31.391298

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb622ee85325'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'statistic',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('service', sa.String(length=32), nullable=False),
        sa.Column('description', sa.String(length=512), nullable=False),
        sa.Column('created_time', postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    # ### end Alembic commands ###
