"""init

Revision ID: 397dc767527f
Revises: 
Create Date: 2023-05-24 20:06:40.491828

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '397dc767527f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'note',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=80), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('created_date', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('author_id', sa.UUID(), nullable=False),
        sa.Column('namespace_id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
