apiVersion: v2
name: services-chart
type: application
version: 1.0.0
dependencies:
  - name: service-chart
    version: 1.0.0
    alias: gateway_service
  - name: service-chart
    version: 1.0.0
    alias: notes_service
  - name: service-chart
    version: 1.0.0
    alias: category_service
  - name: service-chart
    version: 1.0.0
    alias: namespace_service
  - name: service-chart
    version: 1.0.0
    alias: statistic_service
  - name: service-chart
    version: 1.0.0
    alias: identity_provider
  - name: service-chart
    version: 1.0.0
    alias: frontend